#!/bin/sh
# Generates conf.d/00-geo.caddy on stdout from ipdeny's aggregated zone file.
# ipdeny 의 집계 존 파일로 conf.d/00-geo.caddy 를 표준출력에 생성한다.
# refer to docs/snippets.md
#
#   ./tools/geo-gen.sh <country-code> [always-allow-cidr ...] > conf.d/00-geo.caddy
#   ./tools/geo-gen.sh kr 203.0.113.0/24 > conf.d/00-geo.caddy

set -eu

CC="${1:-}"
[ -n "$CC" ] || { echo "usage: $0 <country-code> [always-allow-cidr ...]" >&2; exit 2; }
shift

SRC="https://www.ipdeny.com/ipblocks/data/aggregated/${CC}-aggregated.zone"

ZONE=$(curl -fsS "$SRC") || { echo "fetch failed: $SRC" >&2; exit 1; }
PREFIXES=$(printf '%s\n' "$ZONE" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$')
COUNT=$(printf '%s\n' "$PREFIXES" | wc -l | tr -d ' ')
[ "$COUNT" -gt 0 ] || { echo "no prefixes parsed from $SRC" >&2; exit 1; }

ALL=$(printf '%s %s' "$*" "$(printf '%s\n' "$PREFIXES" | tr '\n' ' ')" | tr -s ' ' | sed 's/^ //;s/ $//')

cat <<HEADER
# Drops traffic from outside $CC. Generated by tools/geo-gen.sh — do not edit by hand.
# $CC 밖에서 오는 접근 차단. tools/geo-gen.sh 가 생성한다. 직접 편집하지 말 것.
# refer to docs/snippets.md
#
# source: $SRC
# built:  $(date -Iseconds)   $CC prefixes: $COUNT (+ $# always-allowed)
(geo-allow) {
	@geo_deny not remote_ip $ALL
	handle @geo_deny {
		log_append block_reason "geo-denied"
		respond 444
	}
}
HEADER
